coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 10%
        # 排除不需要检查的目录
        flags:
          - ignore-paths
        ignore:
          - "cmd/"
          - "server/"