name: Codecov Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-report:
    runs-on: ubuntu-latest
    name: Build, Test, and Report Coverage
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"

      - name: Build
        run: go build -v ./...

      - name: Test Coverage
        run: sudo go test ./... -race -coverprofile=coverage.out -covermode=atomic -v

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out
          flags: unittests
          name: codecov-umbrella
          verbose: true

      # - name: Codacy Coverage Reporter
      #   uses: codacy/codacy-coverage-reporter-action@v1
      #   with:
      #     #language: "go"
      #     project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
      #     #coverage-reports: ./coverage.out
